name: 'Merge Protect'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'main-preview'
        run: |
          echo "ERROR: You can only merge to main from main-preview."
          exit 1
